export const WAITING_FOR_LOANER = 'WAITING_FOR_LOANER'
export const WAITING_FOR_DEBTOR = 'WAITING_FOR_DEBTOR'

export const REJECT_BY_LOANER = 'REJECT_BY_LOANER'
export const REJECT_BY_DEBTOR = 'REJECT_BY_DEBTOR'

export const ACCEPTED_BY_LOANER = 'ACCEPTED_BY_LOANER'
export const ACCEPTED_BY_DEBTOR = 'ACCEPTED_BY_DEBTOR'

export const EXPIRED_BY_LOANER = 'EXPIRED_BY_LOANER'
export const EXPIRED_BY_DEBTOR = 'EXPIRED_BY_DEBTOR'

export const LOAN_REQUESTS_TYPES = [WAITING_FOR_DEBTOR, REJECT_BY_LOANER, REJECT_BY_DEBTOR, WAITING_FOR_LOANER, ACCEPTED_BY_LOANER, ACCEPTED_BY_DEBTOR,EXPIRED_BY_LOANER,EXPIRED_BY_DEBTOR]